services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: stream-backend
    ports:
      - "5000:5000"
    volumes:
      - video_uploads:/app/uploads
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: stream-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: always

  admin:
    build: ./Admin
    container_name: stream-admin
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: always

volumes:
  video_uploads:
